spring:

  application:
    name: generalroad

  datasource:
    url: ENC(JpPRZirAmOWZXeT85cnR/dF1TmPBwcmssfyI0gKYhB0zBP2O4MpoJ4L+5z0AD59g5Jubbm2Xzhks0C1st/Eeh2hkPx2PvmIeZ2/z+/ruC4aJohVh29qu2y9lZIO/FzVhHxwBCn1yQxOACOT9pXvPIA==)
    username: ENC(dDt52/LnU56lJ4yXz+SZ6/2vIqmG74xkCNCTfmEZf0nEysdtG/LSEnrqWVpAfwiO)
    password: ENC(WEeDK/htKQKT4t8NWtDOG4GDjLRaN0HJXgYY8dLSwHEgSyeEqOuqLyG5+hr7U3rk)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL

jasypt:
  encryptor:
    password: gormangi

server:
  port: 14010