spring:

  application:
    name: generalroad

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@gormangi_high?TNS_ADMIN=Wallet_gormangi
    username: ENC(bYOMp4VKYZ1axhd9vbRdR3eBb1OJUZqOPtoHAH6loN5xNhvwA/Wm/o0rvfAUX2w2)
    password: ENC(JhfvY/CkdgPO0lCVSVqso5YIwM83bhhRPwD3YkAZg/ayGX9hy4rM0iUuLvXDSXZx)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

jasypt:
  encryptor:
    password: gormangi

server:
  port: 14010