spring:

  application:
    name: generalroad

  datasource:
    url: ENC(e/j/4MvvtOj332PpuOI/b9HaWvA2rAlI5tAOsiMYP1pYkvwaUmg+okmybhESv77fDcbe1bAxE6M3zD7KC9SkjjSMZXHwkSjkhQ02cs2ixMI2Ob8c/8m8Y8SsfUNnNCubgcM9PrwDHBnkRJhW1wHxatL0zzjZGbgpSOXgE/xNuLk=)
    username: ENC(bYOMp4VKYZ1axhd9vbRdR3eBb1OJUZqOPtoHAH6loN5xNhvwA/Wm/o0rvfAUX2w2)
    password: ENC(JhfvY/CkdgPO0lCVSVqso5YIwM83bhhRPwD3YkAZg/ayGX9hy4rM0iUuLvXDSXZx)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

jasypt:
  encryptor:
    password: gormangi

server:
  port: 80